-- Seed generic exercise library into ma5_exercises (~142 movements).
-- Safe to re-run: skips rows that already exist for the same title + category.
-- Apply after migrations 003_programs.sql and 004_exercise_category.sql.

with seed (title, category, points_of_performance, video_source, default_param_1, default_param_2) as (
  values
  ('Barbell Bench Press', 'Chest', 'Feet planted, scapulae retracted. Lower with control, press evenly.', 'none', 'reps', 'weight_lb'),
  ('Incline Barbell Bench Press', 'Chest', '', 'none', 'reps', 'weight_lb'),
  ('Decline Bench Press', 'Chest', '', 'none', 'reps', 'weight_lb'),
  ('Dumbbell Bench Press', 'Chest', '', 'none', 'reps', 'weight_lb'),
  ('Incline Dumbbell Press', 'Chest', '', 'none', 'reps', 'weight_lb'),
  ('Decline Dumbbell Press', 'Chest', '', 'none', 'reps', 'weight_lb'),
  ('Dumbbell Fly', 'Chest', '', 'none', 'reps', 'weight_lb'),
  ('Incline Fly', 'Chest', '', 'none', 'reps', 'weight_lb'),
  ('Cable Fly', 'Chest', '', 'none', 'reps', 'weight_lb'),
  ('Pec Deck Fly', 'Chest', '', 'none', 'reps', 'weight_lb'),
  ('Push-Up', 'Chest', '', 'none', 'reps', 'weight_lb'),
  ('Incline Push-Up', 'Chest', '', 'none', 'reps', 'weight_lb'),
  ('Decline Push-Up', 'Chest', '', 'none', 'reps', 'weight_lb'),
  ('Close-Grip Push-Up', 'Chest', '', 'none', 'reps', 'weight_lb'),
  ('Chest Dip', 'Chest', '', 'none', 'reps', 'weight_lb'),
  ('Single-Arm Cable Press', 'Chest', '', 'none', 'reps', 'weight_lb'),
  ('Landmine Press', 'Chest', '', 'none', 'reps', 'weight_lb'),
  ('Pull-Up', 'Back', 'Dead hang, scap pack, pull elbows to ribs until chin clears the bar.', 'none', 'reps', 'weight_lb'),
  ('Chin-Up', 'Back', '', 'none', 'reps', 'weight_lb'),
  ('Lat Pulldown', 'Back', '', 'none', 'reps', 'weight_lb'),
  ('Neutral-Grip Pulldown', 'Back', '', 'none', 'reps', 'weight_lb'),
  ('Seated Cable Row', 'Back', '', 'none', 'reps', 'weight_lb'),
  ('Chest Supported Row', 'Back', '', 'none', 'reps', 'weight_lb'),
  ('Bent Over Barbell Row', 'Back', '', 'none', 'reps', 'weight_lb'),
  ('Pendlay Row', 'Back', '', 'none', 'reps', 'weight_lb'),
  ('One Arm Dumbbell Row', 'Back', '', 'none', 'reps', 'weight_lb'),
  ('T-Bar Row', 'Back', '', 'none', 'reps', 'weight_lb'),
  ('Inverted Row', 'Back', '', 'none', 'reps', 'weight_lb'),
  ('Straight Arm Pulldown', 'Back', '', 'none', 'reps', 'weight_lb'),
  ('Face Pull', 'Back', '', 'none', 'reps', 'weight_lb'),
  ('Rear Delt Fly', 'Back', '', 'none', 'reps', 'weight_lb'),
  ('Dumbbell Pullover', 'Back', '', 'none', 'reps', 'weight_lb'),
  ('Overhead Press', 'Shoulders', '', 'none', 'reps', 'weight_lb'),
  ('Dumbbell Shoulder Press', 'Shoulders', '', 'none', 'reps', 'weight_lb'),
  ('Arnold Press', 'Shoulders', '', 'none', 'reps', 'weight_lb'),
  ('Push Press', 'Shoulders', '', 'none', 'reps', 'weight_lb'),
  ('Lateral Raise', 'Shoulders', '', 'none', 'reps', 'weight_lb'),
  ('Front Raise', 'Shoulders', '', 'none', 'reps', 'weight_lb'),
  ('Rear Delt Fly', 'Shoulders', '', 'none', 'reps', 'weight_lb'),
  ('Cuban Press', 'Shoulders', '', 'none', 'reps', 'weight_lb'),
  ('Upright Row', 'Shoulders', '', 'none', 'reps', 'weight_lb'),
  ('Landmine Press', 'Shoulders', '', 'none', 'reps', 'weight_lb'),
  ('Back Squat', 'Legs', 'Bar on upper back. Feet shoulder-width, toes slightly out. Brace, sit between the hips, drive up.', 'none', 'reps', 'weight_lb'),
  ('Front Squat', 'Legs', '', 'none', 'reps', 'weight_lb'),
  ('Goblet Squat', 'Legs', '', 'none', 'reps', 'weight_lb'),
  ('Bulgarian Split Squat', 'Legs', '', 'none', 'reps', 'weight_lb'),
  ('Walking Lunge', 'Legs', '', 'none', 'reps', 'weight_lb'),
  ('Reverse Lunge', 'Legs', '', 'none', 'reps', 'weight_lb'),
  ('Step-Up', 'Legs', '', 'none', 'reps', 'weight_lb'),
  ('Leg Press', 'Legs', '', 'none', 'reps', 'weight_lb'),
  ('Hack Squat', 'Legs', '', 'none', 'reps', 'weight_lb'),
  ('Romanian Deadlift', 'Legs', '', 'none', 'reps', 'weight_lb'),
  ('Stiff-Leg Deadlift', 'Legs', '', 'none', 'reps', 'weight_lb'),
  ('Conventional Deadlift', 'Legs', 'Bar over mid-foot. Hinge, brace, push the floor away. Keep the bar close.', 'none', 'reps', 'weight_lb'),
  ('Trap Bar Deadlift', 'Legs', '', 'none', 'reps', 'weight_lb'),
  ('Hip Thrust', 'Legs', '', 'none', 'reps', 'weight_lb'),
  ('Glute Bridge', 'Legs', '', 'none', 'reps', 'weight_lb'),
  ('Leg Curl', 'Legs', '', 'none', 'reps', 'weight_lb'),
  ('Leg Extension', 'Legs', '', 'none', 'reps', 'weight_lb'),
  ('Calf Raise', 'Legs', '', 'none', 'reps', 'weight_lb'),
  ('Seated Calf Raise', 'Legs', '', 'none', 'reps', 'weight_lb'),
  ('Nordic Curl', 'Hamstrings / Glutes', '', 'none', 'reps', 'weight_lb'),
  ('Good Morning', 'Hamstrings / Glutes', '', 'none', 'reps', 'weight_lb'),
  ('Single Leg RDL', 'Hamstrings / Glutes', '', 'none', 'reps', 'weight_lb'),
  ('Cable Pull Through', 'Hamstrings / Glutes', '', 'none', 'reps', 'weight_lb'),
  ('Reverse Hyper', 'Hamstrings / Glutes', '', 'none', 'reps', 'weight_lb'),
  ('Kettlebell Swing', 'Hamstrings / Glutes', '', 'none', 'reps', 'weight_lb'),
  ('Barbell Curl', 'Arms', '', 'none', 'reps', 'weight_lb'),
  ('EZ Bar Curl', 'Arms', '', 'none', 'reps', 'weight_lb'),
  ('Dumbbell Curl', 'Arms', '', 'none', 'reps', 'weight_lb'),
  ('Hammer Curl', 'Arms', '', 'none', 'reps', 'weight_lb'),
  ('Incline Curl', 'Arms', '', 'none', 'reps', 'weight_lb'),
  ('Concentration Curl', 'Arms', '', 'none', 'reps', 'weight_lb'),
  ('Preacher Curl', 'Arms', '', 'none', 'reps', 'weight_lb'),
  ('Rope Curl', 'Arms', '', 'none', 'reps', 'weight_lb'),
  ('Skull Crusher', 'Arms', '', 'none', 'reps', 'weight_lb'),
  ('Rope Pushdown', 'Arms', '', 'none', 'reps', 'weight_lb'),
  ('Overhead Triceps Extension', 'Arms', '', 'none', 'reps', 'weight_lb'),
  ('Close Grip Bench Press', 'Arms', '', 'none', 'reps', 'weight_lb'),
  ('Bench Dip', 'Arms', '', 'none', 'reps', 'weight_lb'),
  ('Plank', 'Core', 'Brace ribs down, glutes on, long spine. Breathe without sagging.', 'none', 'reps', 'weight_lb'),
  ('Side Plank', 'Core', '', 'none', 'reps', 'weight_lb'),
  ('Dead Bug', 'Core', '', 'none', 'reps', 'weight_lb'),
  ('Bird Dog', 'Core', '', 'none', 'reps', 'weight_lb'),
  ('Hanging Leg Raise', 'Core', '', 'none', 'reps', 'weight_lb'),
  ('Reverse Crunch', 'Core', '', 'none', 'reps', 'weight_lb'),
  ('Bicycle Crunch', 'Core', '', 'none', 'reps', 'weight_lb'),
  ('Russian Twist', 'Core', '', 'none', 'reps', 'weight_lb'),
  ('Pallof Press', 'Core', '', 'none', 'reps', 'weight_lb'),
  ('Cable Crunch', 'Core', '', 'none', 'reps', 'weight_lb'),
  ('Ab Wheel Rollout', 'Core', '', 'none', 'reps', 'weight_lb'),
  ('Mountain Climbers', 'Core', '', 'none', 'reps', 'weight_lb'),
  ('Box Jump', 'Plyometrics', '', 'none', 'reps', 'weight_lb'),
  ('Broad Jump', 'Plyometrics', '', 'none', 'reps', 'weight_lb'),
  ('Depth Jump', 'Plyometrics', '', 'none', 'reps', 'weight_lb'),
  ('Lateral Bounds', 'Plyometrics', '', 'none', 'reps', 'weight_lb'),
  ('Skater Jump', 'Plyometrics', '', 'none', 'reps', 'weight_lb'),
  ('Split Squat Jump', 'Plyometrics', '', 'none', 'reps', 'weight_lb'),
  ('Tuck Jump', 'Plyometrics', '', 'none', 'reps', 'weight_lb'),
  ('A Skip', 'Speed & Agility', '', 'none', 'reps', 'weight_lb'),
  ('B Skip', 'Speed & Agility', '', 'none', 'reps', 'weight_lb'),
  ('High Knees', 'Speed & Agility', '', 'none', 'reps', 'weight_lb'),
  ('Butt Kicks', 'Speed & Agility', '', 'none', 'reps', 'weight_lb'),
  ('Carioca', 'Speed & Agility', '', 'none', 'reps', 'weight_lb'),
  ('Lateral Shuffle', 'Speed & Agility', '', 'none', 'reps', 'weight_lb'),
  ('5-10-5 Shuttle', 'Speed & Agility', '', 'none', 'reps', 'weight_lb'),
  ('Pro Agility', 'Speed & Agility', '', 'none', 'reps', 'weight_lb'),
  ('Ladder Drills', 'Speed & Agility', '', 'none', 'reps', 'weight_lb'),
  ('Cone Weave', 'Speed & Agility', '', 'none', 'reps', 'weight_lb'),
  ('Power Clean', 'Olympic Lifts', '', 'none', 'reps', 'weight_lb'),
  ('Hang Clean', 'Olympic Lifts', '', 'none', 'reps', 'weight_lb'),
  ('Clean Pull', 'Olympic Lifts', '', 'none', 'reps', 'weight_lb'),
  ('Snatch', 'Olympic Lifts', '', 'none', 'reps', 'weight_lb'),
  ('Hang Snatch', 'Olympic Lifts', '', 'none', 'reps', 'weight_lb'),
  ('Push Jerk', 'Olympic Lifts', '', 'none', 'reps', 'weight_lb'),
  ('Split Jerk', 'Olympic Lifts', '', 'none', 'reps', 'weight_lb'),
  ('High Pull', 'Olympic Lifts', '', 'none', 'reps', 'weight_lb'),
  ('Battle Rope', 'Conditioning', '', 'none', 'reps', 'weight_lb'),
  ('Sled Push', 'Conditioning', '', 'none', 'reps', 'weight_lb'),
  ('Sled Pull', 'Conditioning', '', 'none', 'reps', 'weight_lb'),
  ('Farmer Carry', 'Conditioning', '', 'none', 'reps', 'weight_lb'),
  ('Sandbag Carry', 'Conditioning', '', 'none', 'reps', 'weight_lb'),
  ('Assault Bike Sprint', 'Conditioning', '', 'none', 'reps', 'weight_lb'),
  ('Row Erg Sprint', 'Conditioning', '', 'none', 'reps', 'weight_lb'),
  ('Ski Erg', 'Conditioning', '', 'none', 'reps', 'weight_lb'),
  ('Burpees', 'Conditioning', '', 'none', 'reps', 'weight_lb'),
  ('Jump Rope', 'Conditioning', '', 'none', 'reps', 'weight_lb'),
  ('World''s Greatest Stretch', 'Mobility', '', 'none', 'reps', 'weight_lb'),
  ('Hip Flexor Stretch', 'Mobility', '', 'none', 'reps', 'weight_lb'),
  ('Couch Stretch', 'Mobility', '', 'none', 'reps', 'weight_lb'),
  ('Thoracic Rotation', 'Mobility', '', 'none', 'reps', 'weight_lb'),
  ('Cat Cow', 'Mobility', '', 'none', 'reps', 'weight_lb'),
  ('Child''s Pose', 'Mobility', '', 'none', 'reps', 'weight_lb'),
  ('Band Shoulder Stretch', 'Mobility', '', 'none', 'reps', 'weight_lb'),
  ('Hamstring Stretch', 'Mobility', '', 'none', 'reps', 'weight_lb'),
  ('Adductor Rockback', 'Mobility', '', 'none', 'reps', 'weight_lb'),
  ('Foam Roll Quads', 'Recovery', '', 'none', 'reps', 'weight_lb'),
  ('Foam Roll IT Band', 'Recovery', '', 'none', 'reps', 'weight_lb'),
  ('Foam Roll Lats', 'Recovery', '', 'none', 'reps', 'weight_lb'),
  ('Lacrosse Ball Pec Release', 'Recovery', '', 'none', 'reps', 'weight_lb'),
  ('Breathing Drill', 'Recovery', '', 'none', 'reps', 'weight_lb'),
  ('Diaphragmatic Breathing', 'Recovery', '', 'none', 'reps', 'weight_lb')
)
insert into public.ma5_exercises (
  title,
  category,
  points_of_performance,
  video_source,
  default_param_1,
  default_param_2
)
select
  s.title,
  s.category,
  s.points_of_performance,
  s.video_source,
  s.default_param_1,
  s.default_param_2
from seed s
where not exists (
  select 1
  from public.ma5_exercises e
  where e.title = s.title
    and e.category = s.category
);
