export const MA5_TABLES = {
  profiles: "ma5_profiles",
  userRoles: "ma5_user_roles",
  notifications: "ma5_notifications",
  classTypes: "ma5_class_types",
  products: "ma5_products",
  prices: "ma5_prices",
  checkoutSessions: "ma5_checkout_sessions",
  payments: "ma5_payments",
  subscriptions: "ma5_subscriptions",
  invoices: "ma5_invoices",
  refunds: "ma5_refunds",
  sessions: "ma5_sessions",
  bookings: "ma5_bookings",
  memberships: "ma5_memberships",
  exercises: "ma5_exercises",
  workouts: "ma5_workouts",
  workoutBlocks: "ma5_workout_blocks",
  workoutBlockSets: "ma5_workout_block_sets",
  programs: "ma5_programs",
  programDays: "ma5_program_days",
  teams: "ma5_teams",
  teamMembers: "ma5_team_members",
  programAssignments: "ma5_program_assignments",
  calendarEntries: "ma5_calendar_entries",
  workoutCompletions: "ma5_workout_completions",
  clientWaivers: "ma5_client_waivers",
  facilitySettings: "ma5_facility_settings",
  messageThreads: "ma5_message_threads",
  messages: "ma5_messages",
  messageThreadReads: "ma5_message_thread_reads",
  announcements: "ma5_announcements",
  announcementRecipients: "ma5_announcement_recipients",
  pushSubscriptions: "ma5_push_subscriptions",
  visitorSessions: "ma5_visitor_sessions",
  leads: "ma5_leads",
  memberGoals: "ma5_member_goals",
  progressPhotos: "ma5_progress_photos",
} as const;

export type Ma5TableName = (typeof MA5_TABLES)[keyof typeof MA5_TABLES];
