import type {
  CampaignRow,
  MarketingDashboard,
  MarketingLead,
  MemberAttribution,
} from "@/features/marketing/types";

function daysAgo(d: number): string {
  return new Date(Date.now() - d * 24 * 60 * 60 * 1000).toISOString();
}

export const DEMO_LEADS: MarketingLead[] = [
  {
    id: "lead-1",
    visitorId: "11111111-1111-4111-8111-111111111111",
    name: "Sam Rivera",
    email: "sam.rivera@example.com",
    phone: "(317) 555-0142",
    message: "Interested in semi-private training.",
    utmSource: "instagram",
    utmMedium: "social",
    utmCampaign: "spring_strength",
    utmTerm: null,
    utmContent: "reel_a",
    landingPage: "/?utm_source=instagram&utm_medium=social&utm_campaign=spring_strength",
    referrer: "https://instagram.com/",
    status: "new",
    convertedProfileId: null,
    convertedAt: null,
    createdAt: daysAgo(1),
  },
  {
    id: "lead-2",
    visitorId: "22222222-2222-4222-8222-222222222222",
    name: "Jordan Lee",
    email: "jordan.lee@example.com",
    phone: null,
    message: "Looking for youth speed work.",
    utmSource: "google",
    utmMedium: "cpc",
    utmCampaign: "avon_performance",
    utmTerm: "personal trainer avon",
    utmContent: "ad_1",
    landingPage: "/training?utm_source=google&utm_medium=cpc&utm_campaign=avon_performance",
    referrer: "https://www.google.com/",
    status: "contacted",
    convertedProfileId: null,
    convertedAt: null,
    createdAt: daysAgo(4),
  },
  {
    id: "lead-3",
    visitorId: "33333333-3333-4333-8333-333333333333",
    name: "Alex Chen",
    email: "alex.chen@example.com",
    phone: "(317) 555-0199",
    message: null,
    utmSource: "facebook",
    utmMedium: "paid_social",
    utmCampaign: "spring_strength",
    utmTerm: null,
    utmContent: "carousel",
    landingPage: "/contact?utm_source=facebook&utm_medium=paid_social&utm_campaign=spring_strength",
    referrer: "https://facebook.com/",
    status: "converted",
    convertedProfileId: "demo-client",
    convertedAt: daysAgo(12),
    createdAt: daysAgo(20),
  },
  {
    id: "lead-4",
    visitorId: null,
    name: "Morgan Blake",
    email: "morgan.blake@example.com",
    phone: null,
    message: "Walk-in referral from a friend.",
    utmSource: "referral",
    utmMedium: "word_of_mouth",
    utmCampaign: null,
    utmTerm: null,
    utmContent: null,
    landingPage: "/contact",
    referrer: null,
    status: "qualified",
    convertedProfileId: null,
    convertedAt: null,
    createdAt: daysAgo(7),
  },
];

export const DEMO_CAMPAIGNS: CampaignRow[] = [
  {
    campaign: "spring_strength",
    source: "instagram",
    medium: "social",
    visitors: 420,
    leads: 28,
    members: 6,
    conversionRate: 21.4,
  },
  {
    campaign: "avon_performance",
    source: "google",
    medium: "cpc",
    visitors: 310,
    leads: 19,
    members: 5,
    conversionRate: 26.3,
  },
  {
    campaign: "(direct)",
    source: "(direct)",
    medium: "(none)",
    visitors: 180,
    leads: 8,
    members: 2,
    conversionRate: 25,
  },
];

export const DEMO_MARKETING_DASHBOARD: MarketingDashboard = {
  visitorsToday: 47,
  visitorsThisMonth: 1284,
  leads: DEMO_LEADS.length,
  conversionRate: 25,
  membersAcquired: 13,
  topCampaign: "spring_strength",
  trafficSources: [
    { label: "Instagram", value: 38 },
    { label: "Google", value: 29 },
    { label: "Direct", value: 18 },
    { label: "Facebook", value: 10 },
    { label: "Referral", value: 5 },
  ],
  visitorsOverTime: [
    { label: "Mon", value: 42 },
    { label: "Tue", value: 55 },
    { label: "Wed", value: 48 },
    { label: "Thu", value: 61 },
    { label: "Fri", value: 70 },
    { label: "Sat", value: 88 },
    { label: "Sun", value: 52 },
  ],
  leadFunnel: [
    { label: "Visitors", value: 1284 },
    { label: "Leads", value: 55 },
    { label: "Contacted", value: 32 },
    { label: "Members", value: 13 },
  ],
  campaignPerformance: DEMO_CAMPAIGNS,
};

export const DEMO_MEMBER_ATTRIBUTION: MemberAttribution = {
  originalSource: "facebook",
  originalMedium: "paid_social",
  originalCampaign: "spring_strength",
  landingPage: "/contact?utm_source=facebook&utm_medium=paid_social&utm_campaign=spring_strength",
  leadDate: daysAgo(20),
  referrer: "https://facebook.com/",
};
