/**
 * Generated from Signal Works Supabase PostgREST OpenAPI.
 * Regenerate: npm run gen:types
 * Project: gezdzzqnylloaxcmuzvm (post-035 schema)
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      "agreement_acceptances": {
        Row: {
          id: string;
          tenant_id: string;
          user_id?: string;
          offer_id?: string;
          legal_document_id: string;
          document_version: string;
          accepted_name: string;
          accepted_email: string;
          accepted_at: string;
          ip_address?: string;
          user_agent?: string;
          document_snapshot_html: string;
          document_hash: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          user_id?: string;
          offer_id?: string;
          legal_document_id: string;
          document_version: string;
          accepted_name: string;
          accepted_email: string;
          accepted_at: string;
          ip_address?: string;
          user_agent?: string;
          document_snapshot_html: string;
          document_hash: string;
          created_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          user_id?: string | null;
          offer_id?: string | null;
          legal_document_id?: string | null;
          document_version?: string | null;
          accepted_name?: string | null;
          accepted_email?: string | null;
          accepted_at?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          document_snapshot_html?: string | null;
          document_hash?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      "client_offer_items": {
        Row: {
          id: string;
          offer_id: string;
          tenant_id: string;
          item_type: string;
          name: string;
          description?: string;
          quantity: number;
          unit_amount_cents: number;
          billing_type: string;
          billing_interval?: string;
          billing_interval_count: number;
          discount_type?: string;
          discount_amount_cents?: number;
          discount_percent?: number;
          discount_duration_type?: string;
          discount_duration_months?: number;
          stripe_product_id?: string;
          stripe_price_id?: string;
          stripe_coupon_id?: string;
          is_optional: boolean;
          is_selected: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
          metadata: unknown;
        };
        Insert: {
          id?: string;
          offer_id: string;
          tenant_id: string;
          item_type: string;
          name: string;
          description?: string;
          quantity: number;
          unit_amount_cents: number;
          billing_type: string;
          billing_interval?: string;
          billing_interval_count: number;
          discount_type?: string;
          discount_amount_cents?: number;
          discount_percent?: number;
          discount_duration_type?: string;
          discount_duration_months?: number;
          stripe_product_id?: string;
          stripe_price_id?: string;
          stripe_coupon_id?: string;
          is_optional: boolean;
          is_selected: boolean;
          sort_order: number;
          created_at?: string;
          updated_at?: string;
          metadata: unknown;
        };
        Update: {
          id?: string | null;
          offer_id?: string | null;
          tenant_id?: string | null;
          item_type?: string | null;
          name?: string | null;
          description?: string | null;
          quantity?: number | null;
          unit_amount_cents?: number | null;
          billing_type?: string | null;
          billing_interval?: string | null;
          billing_interval_count?: number | null;
          discount_type?: string | null;
          discount_amount_cents?: number | null;
          discount_percent?: number | null;
          discount_duration_type?: string | null;
          discount_duration_months?: number | null;
          stripe_product_id?: string | null;
          stripe_price_id?: string | null;
          stripe_coupon_id?: string | null;
          is_optional?: boolean | null;
          is_selected?: boolean | null;
          sort_order?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
          metadata?: unknown | null;
        };
        Relationships: [];
      };
      "client_offers": {
        Row: {
          id: string;
          tenant_id: string;
          title: string;
          description?: string;
          status: string;
          currency: string;
          valid_from?: string;
          expires_at?: string;
          terms_document_id?: string;
          requires_terms_acceptance: boolean;
          subtotal_cents: number;
          discount_total_cents: number;
          initial_total_cents: number;
          recurring_total_cents: number;
          created_by?: string;
          published_at?: string;
          accepted_at?: string;
          purchased_at?: string;
          created_at: string;
          updated_at: string;
          sow_document_id?: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          title: string;
          description?: string;
          status: string;
          currency: string;
          valid_from?: string;
          expires_at?: string;
          terms_document_id?: string;
          requires_terms_acceptance: boolean;
          subtotal_cents: number;
          discount_total_cents: number;
          initial_total_cents: number;
          recurring_total_cents: number;
          created_by?: string;
          published_at?: string;
          accepted_at?: string;
          purchased_at?: string;
          created_at?: string;
          updated_at?: string;
          sow_document_id?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          title?: string | null;
          description?: string | null;
          status?: string | null;
          currency?: string | null;
          valid_from?: string | null;
          expires_at?: string | null;
          terms_document_id?: string | null;
          requires_terms_acceptance?: boolean | null;
          subtotal_cents?: number | null;
          discount_total_cents?: number | null;
          initial_total_cents?: number | null;
          recurring_total_cents?: number | null;
          created_by?: string | null;
          published_at?: string | null;
          accepted_at?: string | null;
          purchased_at?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          sow_document_id?: string | null;
        };
        Relationships: [];
      };
      "client_pipeline": {
        Row: {
          id: string;
          tenant_id: string;
          business_name: string;
          contact_name: string;
          status: string;
          last_conversation?: string;
          plan?: string;
          created_at: string;
          updated_at: string;
          contact_email?: string;
          phone?: string;
          website_url?: string;
          estimated_monthly_value_cents?: number;
          next_follow_up_date?: string;
          last_contacted_at?: string;
          tags: string[];
        };
        Insert: {
          id?: string;
          tenant_id: string;
          business_name: string;
          contact_name: string;
          status: string;
          last_conversation?: string;
          plan?: string;
          created_at?: string;
          updated_at?: string;
          contact_email?: string;
          phone?: string;
          website_url?: string;
          estimated_monthly_value_cents?: number;
          next_follow_up_date?: string;
          last_contacted_at?: string;
          tags: string[];
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          business_name?: string | null;
          contact_name?: string | null;
          status?: string | null;
          last_conversation?: string | null;
          plan?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          contact_email?: string | null;
          phone?: string | null;
          website_url?: string | null;
          estimated_monthly_value_cents?: number | null;
          next_follow_up_date?: string | null;
          last_contacted_at?: string | null;
          tags?: string[] | null;
        };
        Relationships: [];
      };
      "documents": {
        Row: {
          id: string;
          tenant_id: string;
          title: string;
          description?: string;
          file_url: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          title: string;
          description?: string;
          file_url: string;
          created_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          title?: string | null;
          description?: string | null;
          file_url?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      "legal_documents": {
        Row: {
          id: string;
          tenant_id?: string;
          document_type: string;
          title: string;
          version: string;
          content_html: string;
          content_text?: string;
          effective_date?: string;
          active: boolean;
          created_by?: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id?: string;
          document_type: string;
          title: string;
          version: string;
          content_html: string;
          content_text?: string;
          effective_date?: string;
          active: boolean;
          created_by?: string;
          created_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          document_type?: string | null;
          title?: string | null;
          version?: string | null;
          content_html?: string | null;
          content_text?: string | null;
          effective_date?: string | null;
          active?: boolean | null;
          created_by?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_announcement_recipients": {
        Row: {
          id: string;
          announcement_id: string;
          client_id: string;
          user_id?: string;
          delivered_at?: string;
          read_at?: string;
          email_sent_at?: string;
          push_sent_at?: string;
        };
        Insert: {
          id?: string;
          announcement_id: string;
          client_id: string;
          user_id?: string;
          delivered_at?: string;
          read_at?: string;
          email_sent_at?: string;
          push_sent_at?: string;
        };
        Update: {
          id?: string | null;
          announcement_id?: string | null;
          client_id?: string | null;
          user_id?: string | null;
          delivered_at?: string | null;
          read_at?: string | null;
          email_sent_at?: string | null;
          push_sent_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_announcements": {
        Row: {
          id: string;
          tenant_id: string;
          created_by: string;
          title: string;
          body: string;
          audience_type: string;
          audience_filter?: unknown;
          priority: string;
          status: string;
          publish_at?: string;
          expires_at?: string;
          link_url?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          created_by: string;
          title: string;
          body: string;
          audience_type: string;
          audience_filter?: unknown;
          priority: string;
          status: string;
          publish_at?: string;
          expires_at?: string;
          link_url?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          created_by?: string | null;
          title?: string | null;
          body?: string | null;
          audience_type?: string | null;
          audience_filter?: unknown | null;
          priority?: string | null;
          status?: string | null;
          publish_at?: string | null;
          expires_at?: string | null;
          link_url?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_bookings": {
        Row: {
          id: string;
          tenant_id: string;
          session_id: string;
          user_id: string;
          confirmation_number: string;
          status: string;
          payment_status: string;
          amount_cents: number;
          stripe_checkout_session_id?: string;
          notes?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          session_id: string;
          user_id: string;
          confirmation_number: string;
          status: string;
          payment_status: string;
          amount_cents: number;
          stripe_checkout_session_id?: string;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          session_id?: string | null;
          user_id?: string | null;
          confirmation_number?: string | null;
          status?: string | null;
          payment_status?: string | null;
          amount_cents?: number | null;
          stripe_checkout_session_id?: string | null;
          notes?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_calendar_entries": {
        Row: {
          id: string;
          tenant_id: string;
          entry_date: string;
          workout_id?: string;
          title: string;
          publish_status: string;
          source: string;
          client_user_id?: string;
          team_id?: string;
          program_assignment_id?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          entry_date: string;
          workout_id?: string;
          title: string;
          publish_status: string;
          source: string;
          client_user_id?: string;
          team_id?: string;
          program_assignment_id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          entry_date?: string | null;
          workout_id?: string | null;
          title?: string | null;
          publish_status?: string | null;
          source?: string | null;
          client_user_id?: string | null;
          team_id?: string | null;
          program_assignment_id?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_checkout_sessions": {
        Row: {
          id: string;
          tenant_id: string;
          stripe_checkout_session_id: string;
          user_id?: string;
          product_id?: string;
          mode: string;
          status: string;
          amount_total_cents?: number;
          currency?: string;
          stripe_customer_id?: string;
          stripe_payment_intent_id?: string;
          stripe_subscription_id?: string;
          metadata: unknown;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          stripe_checkout_session_id: string;
          user_id?: string;
          product_id?: string;
          mode: string;
          status: string;
          amount_total_cents?: number;
          currency?: string;
          stripe_customer_id?: string;
          stripe_payment_intent_id?: string;
          stripe_subscription_id?: string;
          metadata: unknown;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          stripe_checkout_session_id?: string | null;
          user_id?: string | null;
          product_id?: string | null;
          mode?: string | null;
          status?: string | null;
          amount_total_cents?: number | null;
          currency?: string | null;
          stripe_customer_id?: string | null;
          stripe_payment_intent_id?: string | null;
          stripe_subscription_id?: string | null;
          metadata?: unknown | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_class_types": {
        Row: {
          id: string;
          tenant_id: string;
          slug: string;
          name: string;
          description?: string;
          default_duration_minutes: number;
          default_capacity: number;
          default_price_cents: number;
          active: boolean;
          display_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          slug: string;
          name: string;
          description?: string;
          default_duration_minutes: number;
          default_capacity: number;
          default_price_cents: number;
          active: boolean;
          display_order: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          slug?: string | null;
          name?: string | null;
          description?: string | null;
          default_duration_minutes?: number | null;
          default_capacity?: number | null;
          default_price_cents?: number | null;
          active?: boolean | null;
          display_order?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_client_waivers": {
        Row: {
          id: string;
          tenant_id: string;
          user_id: string;
          waiver_key: string;
          status: string;
          signed_at?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          user_id: string;
          waiver_key: string;
          status: string;
          signed_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          user_id?: string | null;
          waiver_key?: string | null;
          status?: string | null;
          signed_at?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_community_posts": {
        Row: {
          id: string;
          tenant_id: string;
          author_user_id: string;
          body: string;
          parent_id?: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          author_user_id: string;
          body: string;
          parent_id?: string;
          created_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          author_user_id?: string | null;
          body?: string | null;
          parent_id?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_exercises": {
        Row: {
          id: string;
          tenant_id: string;
          title: string;
          category: string;
          points_of_performance: string;
          video_source: string;
          video_url?: string;
          video_storage_path?: string;
          video_poster_path?: string;
          default_param_1: string;
          default_param_2: string;
          created_by?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          title: string;
          category: string;
          points_of_performance: string;
          video_source: string;
          video_url?: string;
          video_storage_path?: string;
          video_poster_path?: string;
          default_param_1: string;
          default_param_2: string;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          title?: string | null;
          category?: string | null;
          points_of_performance?: string | null;
          video_source?: string | null;
          video_url?: string | null;
          video_storage_path?: string | null;
          video_poster_path?: string | null;
          default_param_1?: string | null;
          default_param_2?: string | null;
          created_by?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_invoices": {
        Row: {
          id: string;
          tenant_id: string;
          user_id?: string;
          subscription_id?: string;
          stripe_invoice_id: string;
          stripe_subscription_id?: string;
          amount_due_cents: number;
          amount_paid_cents: number;
          currency: string;
          status: string;
          hosted_invoice_url?: string;
          invoice_pdf?: string;
          period_start?: string;
          period_end?: string;
          metadata: unknown;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          user_id?: string;
          subscription_id?: string;
          stripe_invoice_id: string;
          stripe_subscription_id?: string;
          amount_due_cents: number;
          amount_paid_cents: number;
          currency: string;
          status: string;
          hosted_invoice_url?: string;
          invoice_pdf?: string;
          period_start?: string;
          period_end?: string;
          metadata: unknown;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          user_id?: string | null;
          subscription_id?: string | null;
          stripe_invoice_id?: string | null;
          stripe_subscription_id?: string | null;
          amount_due_cents?: number | null;
          amount_paid_cents?: number | null;
          currency?: string | null;
          status?: string | null;
          hosted_invoice_url?: string | null;
          invoice_pdf?: string | null;
          period_start?: string | null;
          period_end?: string | null;
          metadata?: unknown | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_leads": {
        Row: {
          id: string;
          tenant_id: string;
          visitor_id?: string;
          name: string;
          email: string;
          phone?: string;
          message?: string;
          utm_source?: string;
          utm_medium?: string;
          utm_campaign?: string;
          utm_term?: string;
          utm_content?: string;
          landing_page?: string;
          referrer?: string;
          status: string;
          converted_profile_id?: string;
          converted_at?: string;
          invited_at?: string;
          source_path?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          visitor_id?: string;
          name: string;
          email: string;
          phone?: string;
          message?: string;
          utm_source?: string;
          utm_medium?: string;
          utm_campaign?: string;
          utm_term?: string;
          utm_content?: string;
          landing_page?: string;
          referrer?: string;
          status: string;
          converted_profile_id?: string;
          converted_at?: string;
          invited_at?: string;
          source_path?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          visitor_id?: string | null;
          name?: string | null;
          email?: string | null;
          phone?: string | null;
          message?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_term?: string | null;
          utm_content?: string | null;
          landing_page?: string | null;
          referrer?: string | null;
          status?: string | null;
          converted_profile_id?: string | null;
          converted_at?: string | null;
          invited_at?: string | null;
          source_path?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_locations": {
        Row: {
          id: string;
          tenant_id: string;
          slug: string;
          name: string;
          legal_name?: string;
          address_line?: string;
          email?: string;
          timezone: string;
          open_gym_hours?: string;
          coaching_hours?: string;
          hours_summary?: string;
          brand_primary: string;
          logo_storage_path?: string;
          notify_failed_payments: boolean;
          notify_new_signups: boolean;
          notify_message_digest: boolean;
          notify_capacity_warnings: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          slug: string;
          name: string;
          legal_name?: string;
          address_line?: string;
          email?: string;
          timezone: string;
          open_gym_hours?: string;
          coaching_hours?: string;
          hours_summary?: string;
          brand_primary: string;
          logo_storage_path?: string;
          notify_failed_payments: boolean;
          notify_new_signups: boolean;
          notify_message_digest: boolean;
          notify_capacity_warnings: boolean;
          is_active: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          slug?: string | null;
          name?: string | null;
          legal_name?: string | null;
          address_line?: string | null;
          email?: string | null;
          timezone?: string | null;
          open_gym_hours?: string | null;
          coaching_hours?: string | null;
          hours_summary?: string | null;
          brand_primary?: string | null;
          logo_storage_path?: string | null;
          notify_failed_payments?: boolean | null;
          notify_new_signups?: boolean | null;
          notify_message_digest?: boolean | null;
          notify_capacity_warnings?: boolean | null;
          is_active?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_marketing_gallery": {
        Row: {
          id: string;
          tenant_id: string;
          section: string;
          storage_path: string;
          alt_text: string;
          client_name?: string;
          sort_order: number;
          featured: boolean;
          placement?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          section: string;
          storage_path: string;
          alt_text: string;
          client_name?: string;
          sort_order: number;
          featured: boolean;
          placement?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          section?: string | null;
          storage_path?: string | null;
          alt_text?: string | null;
          client_name?: string | null;
          sort_order?: number | null;
          featured?: boolean | null;
          placement?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_member_goals": {
        Row: {
          id: string;
          tenant_id: string;
          user_id: string;
          title: string;
          target_date?: string;
          status: string;
          completed_at?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          user_id: string;
          title: string;
          target_date?: string;
          status: string;
          completed_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          user_id?: string | null;
          title?: string | null;
          target_date?: string | null;
          status?: string | null;
          completed_at?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_memberships": {
        Row: {
          id: string;
          tenant_id: string;
          user_id: string;
          product_id: string;
          status: string;
          stripe_subscription_id?: string;
          stripe_price_id?: string;
          current_period_end?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          user_id: string;
          product_id: string;
          status: string;
          stripe_subscription_id?: string;
          stripe_price_id?: string;
          current_period_end?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          user_id?: string | null;
          product_id?: string | null;
          status?: string | null;
          stripe_subscription_id?: string | null;
          stripe_price_id?: string | null;
          current_period_end?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_message_thread_reads": {
        Row: {
          id: string;
          thread_id: string;
          user_id: string;
          last_read_at: string;
        };
        Insert: {
          id?: string;
          thread_id: string;
          user_id: string;
          last_read_at: string;
        };
        Update: {
          id?: string | null;
          thread_id?: string | null;
          user_id?: string | null;
          last_read_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_message_threads": {
        Row: {
          id: string;
          tenant_id: string;
          client_id: string;
          created_by: string;
          subject?: string;
          status: string;
          last_message_at?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          client_id: string;
          created_by: string;
          subject?: string;
          status: string;
          last_message_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          client_id?: string | null;
          created_by?: string | null;
          subject?: string | null;
          status?: string | null;
          last_message_at?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_messages": {
        Row: {
          id: string;
          tenant_id: string;
          thread_id: string;
          sender_user_id: string;
          sender_role: string;
          body: string;
          created_at: string;
          edited_at?: string;
          deleted_at?: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          thread_id: string;
          sender_user_id: string;
          sender_role: string;
          body: string;
          created_at?: string;
          edited_at?: string;
          deleted_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          thread_id?: string | null;
          sender_user_id?: string | null;
          sender_role?: string | null;
          body?: string | null;
          created_at?: string | null;
          edited_at?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_notifications": {
        Row: {
          id: string;
          tenant_id: string;
          user_id: string;
          title: string;
          body: string;
          href?: string;
          type: string;
          entity_type?: string;
          entity_id?: string;
          read_at?: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          user_id: string;
          title: string;
          body: string;
          href?: string;
          type: string;
          entity_type?: string;
          entity_id?: string;
          read_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          user_id?: string | null;
          title?: string | null;
          body?: string | null;
          href?: string | null;
          type?: string | null;
          entity_type?: string | null;
          entity_id?: string | null;
          read_at?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_payments": {
        Row: {
          id: string;
          tenant_id: string;
          user_id?: string;
          product_id?: string;
          checkout_session_id?: string;
          stripe_payment_intent_id?: string;
          stripe_charge_id?: string;
          stripe_invoice_id?: string;
          amount_cents: number;
          currency: string;
          status: string;
          processing_fee_cents: number;
          net_amount_cents?: number;
          payment_method_type?: string;
          import_source?: string;
          external_payment_id?: string;
          metadata: unknown;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          user_id?: string;
          product_id?: string;
          checkout_session_id?: string;
          stripe_payment_intent_id?: string;
          stripe_charge_id?: string;
          stripe_invoice_id?: string;
          amount_cents: number;
          currency: string;
          status: string;
          processing_fee_cents: number;
          net_amount_cents?: number;
          payment_method_type?: string;
          import_source?: string;
          external_payment_id?: string;
          metadata: unknown;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          user_id?: string | null;
          product_id?: string | null;
          checkout_session_id?: string | null;
          stripe_payment_intent_id?: string | null;
          stripe_charge_id?: string | null;
          stripe_invoice_id?: string | null;
          amount_cents?: number | null;
          currency?: string | null;
          status?: string | null;
          processing_fee_cents?: number | null;
          net_amount_cents?: number | null;
          payment_method_type?: string | null;
          import_source?: string | null;
          external_payment_id?: string | null;
          metadata?: unknown | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_prices": {
        Row: {
          id: string;
          tenant_id: string;
          product_id: string;
          stripe_price_id?: string;
          amount_cents: number;
          currency: string;
          billing_interval?: string;
          active: boolean;
          effective_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          product_id: string;
          stripe_price_id?: string;
          amount_cents: number;
          currency: string;
          billing_interval?: string;
          active: boolean;
          effective_at: string;
          created_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          product_id?: string | null;
          stripe_price_id?: string | null;
          amount_cents?: number | null;
          currency?: string | null;
          billing_interval?: string | null;
          active?: boolean | null;
          effective_at?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_products": {
        Row: {
          id: string;
          tenant_id: string;
          slug: string;
          name: string;
          description?: string;
          product_type: string;
          category?: string;
          payment_type: string;
          status: string;
          price_cents: number;
          currency: string;
          billing_interval?: string;
          session_credits?: number;
          stripe_product_id?: string;
          current_stripe_price_id?: string;
          active: boolean;
          archived_at?: string;
          display_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          slug: string;
          name: string;
          description?: string;
          product_type: string;
          category?: string;
          payment_type: string;
          status: string;
          price_cents: number;
          currency: string;
          billing_interval?: string;
          session_credits?: number;
          stripe_product_id?: string;
          current_stripe_price_id?: string;
          active: boolean;
          archived_at?: string;
          display_order: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          slug?: string | null;
          name?: string | null;
          description?: string | null;
          product_type?: string | null;
          category?: string | null;
          payment_type?: string | null;
          status?: string | null;
          price_cents?: number | null;
          currency?: string | null;
          billing_interval?: string | null;
          session_credits?: number | null;
          stripe_product_id?: string | null;
          current_stripe_price_id?: string | null;
          active?: boolean | null;
          archived_at?: string | null;
          display_order?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_profiles": {
        Row: {
          id: string;
          tenant_id: string;
          email: string;
          full_name?: string;
          preferred_name?: string;
          phone?: string;
          avatar_url?: string;
          active: boolean;
          stripe_customer_id?: string;
          emergency_name?: string;
          emergency_relationship?: string;
          emergency_phone?: string;
          emergency_notes?: string;
          notify_coach_messages: boolean;
          notify_session_reminders: boolean;
          notify_program_updates: boolean;
          notify_billing_alerts: boolean;
          invitation_status: string;
          invited_at?: string;
          invitation_accepted_at?: string;
          last_login_at?: string;
          access_revoked_at?: string;
          admin_notes?: string;
          lead_id?: string;
          acquisition_source?: string;
          acquisition_medium?: string;
          acquisition_campaign?: string;
          acquisition_term?: string;
          acquisition_content?: string;
          acquisition_landing_page?: string;
          acquisition_referrer?: string;
          acquisition_first_seen_at?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          email: string;
          full_name?: string;
          preferred_name?: string;
          phone?: string;
          avatar_url?: string;
          active: boolean;
          stripe_customer_id?: string;
          emergency_name?: string;
          emergency_relationship?: string;
          emergency_phone?: string;
          emergency_notes?: string;
          notify_coach_messages: boolean;
          notify_session_reminders: boolean;
          notify_program_updates: boolean;
          notify_billing_alerts: boolean;
          invitation_status: string;
          invited_at?: string;
          invitation_accepted_at?: string;
          last_login_at?: string;
          access_revoked_at?: string;
          admin_notes?: string;
          lead_id?: string;
          acquisition_source?: string;
          acquisition_medium?: string;
          acquisition_campaign?: string;
          acquisition_term?: string;
          acquisition_content?: string;
          acquisition_landing_page?: string;
          acquisition_referrer?: string;
          acquisition_first_seen_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          email?: string | null;
          full_name?: string | null;
          preferred_name?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          active?: boolean | null;
          stripe_customer_id?: string | null;
          emergency_name?: string | null;
          emergency_relationship?: string | null;
          emergency_phone?: string | null;
          emergency_notes?: string | null;
          notify_coach_messages?: boolean | null;
          notify_session_reminders?: boolean | null;
          notify_program_updates?: boolean | null;
          notify_billing_alerts?: boolean | null;
          invitation_status?: string | null;
          invited_at?: string | null;
          invitation_accepted_at?: string | null;
          last_login_at?: string | null;
          access_revoked_at?: string | null;
          admin_notes?: string | null;
          lead_id?: string | null;
          acquisition_source?: string | null;
          acquisition_medium?: string | null;
          acquisition_campaign?: string | null;
          acquisition_term?: string | null;
          acquisition_content?: string | null;
          acquisition_landing_page?: string | null;
          acquisition_referrer?: string | null;
          acquisition_first_seen_at?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_program_assignments": {
        Row: {
          id: string;
          tenant_id: string;
          program_id?: string;
          client_user_id?: string;
          team_id?: string;
          start_date: string;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          program_id?: string;
          client_user_id?: string;
          team_id?: string;
          start_date: string;
          status: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          program_id?: string | null;
          client_user_id?: string | null;
          team_id?: string | null;
          start_date?: string | null;
          status?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_program_days": {
        Row: {
          id: string;
          program_id: string;
          week_index: number;
          day_index: number;
          workout_id?: string;
        };
        Insert: {
          id?: string;
          program_id: string;
          week_index: number;
          day_index: number;
          workout_id?: string;
        };
        Update: {
          id?: string | null;
          program_id?: string | null;
          week_index?: number | null;
          day_index?: number | null;
          workout_id?: string | null;
        };
        Relationships: [];
      };
      "ma5_programs": {
        Row: {
          id: string;
          tenant_id: string;
          title: string;
          weeks: number;
          created_by?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          title: string;
          weeks: number;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          title?: string | null;
          weeks?: number | null;
          created_by?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_progress_photos": {
        Row: {
          id: string;
          tenant_id: string;
          user_id: string;
          storage_path: string;
          caption?: string;
          taken_at: string;
          metadata: unknown;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          user_id: string;
          storage_path: string;
          caption?: string;
          taken_at: string;
          metadata: unknown;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          user_id?: string | null;
          storage_path?: string | null;
          caption?: string | null;
          taken_at?: string | null;
          metadata?: unknown | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_push_subscriptions": {
        Row: {
          id: string;
          tenant_id: string;
          user_id: string;
          endpoint: string;
          p256dh: string;
          auth: string;
          user_agent?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          user_id: string;
          endpoint: string;
          p256dh: string;
          auth: string;
          user_agent?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          user_id?: string | null;
          endpoint?: string | null;
          p256dh?: string | null;
          auth?: string | null;
          user_agent?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_refunds": {
        Row: {
          id: string;
          tenant_id: string;
          payment_id?: string;
          stripe_refund_id: string;
          stripe_charge_id?: string;
          amount_cents: number;
          currency: string;
          status: string;
          reason?: string;
          metadata: unknown;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          payment_id?: string;
          stripe_refund_id: string;
          stripe_charge_id?: string;
          amount_cents: number;
          currency: string;
          status: string;
          reason?: string;
          metadata: unknown;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          payment_id?: string | null;
          stripe_refund_id?: string | null;
          stripe_charge_id?: string | null;
          amount_cents?: number | null;
          currency?: string | null;
          status?: string | null;
          reason?: string | null;
          metadata?: unknown | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_sessions": {
        Row: {
          id: string;
          tenant_id: string;
          location_id: string;
          class_type_id?: string;
          title: string;
          description?: string;
          starts_at: string;
          ends_at: string;
          timezone: string;
          capacity: number;
          price_cents: number;
          status: string;
          coach_name?: string;
          created_by?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          location_id: string;
          class_type_id?: string;
          title: string;
          description?: string;
          starts_at: string;
          ends_at: string;
          timezone: string;
          capacity: number;
          price_cents: number;
          status: string;
          coach_name?: string;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          location_id?: string | null;
          class_type_id?: string | null;
          title?: string | null;
          description?: string | null;
          starts_at?: string | null;
          ends_at?: string | null;
          timezone?: string | null;
          capacity?: number | null;
          price_cents?: number | null;
          status?: string | null;
          coach_name?: string | null;
          created_by?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_stripe_webhook_events": {
        Row: {
          id: string;
          tenant_id: string;
          stripe_account_id: string;
          stripe_event_id: string;
          event_type: string;
          processed_at?: string;
          payload_hash?: string;
          created_at: string;
          processing_status: string;
          claimed_at?: string;
          failed_at?: string;
          last_error?: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          stripe_account_id: string;
          stripe_event_id: string;
          event_type: string;
          processed_at?: string;
          payload_hash?: string;
          created_at?: string;
          processing_status: string;
          claimed_at?: string;
          failed_at?: string;
          last_error?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          stripe_account_id?: string | null;
          stripe_event_id?: string | null;
          event_type?: string | null;
          processed_at?: string | null;
          payload_hash?: string | null;
          created_at?: string | null;
          processing_status?: string | null;
          claimed_at?: string | null;
          failed_at?: string | null;
          last_error?: string | null;
        };
        Relationships: [];
      };
      "ma5_subscriptions": {
        Row: {
          id: string;
          tenant_id: string;
          user_id: string;
          product_id?: string;
          price_id?: string;
          stripe_subscription_id: string;
          stripe_price_id?: string;
          status: string;
          current_period_start?: string;
          current_period_end?: string;
          cancel_at_period_end: boolean;
          canceled_at?: string;
          metadata: unknown;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          user_id: string;
          product_id?: string;
          price_id?: string;
          stripe_subscription_id: string;
          stripe_price_id?: string;
          status: string;
          current_period_start?: string;
          current_period_end?: string;
          cancel_at_period_end: boolean;
          canceled_at?: string;
          metadata: unknown;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          user_id?: string | null;
          product_id?: string | null;
          price_id?: string | null;
          stripe_subscription_id?: string | null;
          stripe_price_id?: string | null;
          status?: string | null;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean | null;
          canceled_at?: string | null;
          metadata?: unknown | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_team_members": {
        Row: {
          id: string;
          team_id: string;
          user_id: string;
          role: string;
          joined_at: string;
        };
        Insert: {
          id?: string;
          team_id: string;
          user_id: string;
          role: string;
          joined_at: string;
        };
        Update: {
          id?: string | null;
          team_id?: string | null;
          user_id?: string | null;
          role?: string | null;
          joined_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_teams": {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          difficulty?: string;
          created_by?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          name: string;
          difficulty?: string;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          name?: string | null;
          difficulty?: string | null;
          created_by?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_user_roles": {
        Row: {
          id: string;
          tenant_id: string;
          user_id: string;
          role: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          user_id: string;
          role: string;
          created_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          user_id?: string | null;
          role?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_visitor_sessions": {
        Row: {
          visitor_id: string;
          tenant_id: string;
          first_seen: string;
          last_seen: string;
          landing_page?: string;
          referrer?: string;
          utm_source?: string;
          utm_medium?: string;
          utm_campaign?: string;
          utm_term?: string;
          utm_content?: string;
          last_landing_page?: string;
          last_referrer?: string;
          last_utm_source?: string;
          last_utm_medium?: string;
          last_utm_campaign?: string;
          last_utm_term?: string;
          last_utm_content?: string;
          page_views: number;
          is_bot: boolean;
          user_agent?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          visitor_id: string;
          tenant_id: string;
          first_seen: string;
          last_seen: string;
          landing_page?: string;
          referrer?: string;
          utm_source?: string;
          utm_medium?: string;
          utm_campaign?: string;
          utm_term?: string;
          utm_content?: string;
          last_landing_page?: string;
          last_referrer?: string;
          last_utm_source?: string;
          last_utm_medium?: string;
          last_utm_campaign?: string;
          last_utm_term?: string;
          last_utm_content?: string;
          page_views: number;
          is_bot: boolean;
          user_agent?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          visitor_id?: string | null;
          tenant_id?: string | null;
          first_seen?: string | null;
          last_seen?: string | null;
          landing_page?: string | null;
          referrer?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_term?: string | null;
          utm_content?: string | null;
          last_landing_page?: string | null;
          last_referrer?: string | null;
          last_utm_source?: string | null;
          last_utm_medium?: string | null;
          last_utm_campaign?: string | null;
          last_utm_term?: string | null;
          last_utm_content?: string | null;
          page_views?: number | null;
          is_bot?: boolean | null;
          user_agent?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_workout_block_sets": {
        Row: {
          id: string;
          block_id: string;
          set_number: number;
          reps?: number;
          weight_lb?: number;
        };
        Insert: {
          id?: string;
          block_id: string;
          set_number: number;
          reps?: number;
          weight_lb?: number;
        };
        Update: {
          id?: string | null;
          block_id?: string | null;
          set_number?: number | null;
          reps?: number | null;
          weight_lb?: number | null;
        };
        Relationships: [];
      };
      "ma5_workout_blocks": {
        Row: {
          id: string;
          workout_id: string;
          sort_order: number;
          label: string;
          section_title?: string;
          exercise_id: string;
          session_cues: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          workout_id: string;
          sort_order: number;
          label: string;
          section_title?: string;
          exercise_id: string;
          session_cues: string;
          created_at?: string;
        };
        Update: {
          id?: string | null;
          workout_id?: string | null;
          sort_order?: number | null;
          label?: string | null;
          section_title?: string | null;
          exercise_id?: string | null;
          session_cues?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_workout_completions": {
        Row: {
          id: string;
          tenant_id: string;
          calendar_entry_id: string;
          client_user_id: string;
          completed_at: string;
          client_note: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          calendar_entry_id: string;
          client_user_id: string;
          completed_at: string;
          client_note: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          calendar_entry_id?: string | null;
          client_user_id?: string | null;
          completed_at?: string | null;
          client_note?: string | null;
        };
        Relationships: [];
      };
      "ma5_workout_set_logs": {
        Row: {
          id: string;
          tenant_id: string;
          calendar_entry_id: string;
          client_user_id: string;
          workout_block_id: string;
          exercise_id: string;
          set_number: number;
          target_reps?: number;
          reps?: number;
          weight_lb?: number;
          logged_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          calendar_entry_id: string;
          client_user_id: string;
          workout_block_id: string;
          exercise_id: string;
          set_number: number;
          target_reps?: number;
          reps?: number;
          weight_lb?: number;
          logged_at: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          calendar_entry_id?: string | null;
          client_user_id?: string | null;
          workout_block_id?: string | null;
          exercise_id?: string | null;
          set_number?: number | null;
          target_reps?: number | null;
          reps?: number | null;
          weight_lb?: number | null;
          logged_at?: string | null;
        };
        Relationships: [];
      };
      "ma5_workouts": {
        Row: {
          id: string;
          tenant_id: string;
          title: string;
          coach_instructions: string;
          created_by?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          title: string;
          coach_instructions: string;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          title?: string | null;
          coach_instructions?: string | null;
          created_by?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "permissions": {
        Row: {
          id: string;
          name: string;
          description?: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string;
          created_at?: string;
        };
        Update: {
          id?: string | null;
          name?: string | null;
          description?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      "platform_plan_templates": {
        Row: {
          id: string;
          plan_key: string;
          name: string;
          description?: string;
          default_price_cents: number;
          billing_interval: string;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          plan_key: string;
          name: string;
          description?: string;
          default_price_cents: number;
          billing_interval: string;
          sort_order: number;
          is_active: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          plan_key?: string | null;
          name?: string | null;
          description?: string | null;
          default_price_cents?: number | null;
          billing_interval?: string | null;
          sort_order?: number | null;
          is_active?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "platform_product_catalog": {
        Row: {
          id: string;
          product_key: string;
          name: string;
          description?: string;
          category?: string;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          is_paid_add_on: boolean;
          default_add_on_price_cents?: number;
          catalog_kind: string;
          category_group?: string;
          capabilities: string[];
          suggested_add_on_price_cents?: number;
          supports_quantity: boolean;
        };
        Insert: {
          id?: string;
          product_key: string;
          name: string;
          description?: string;
          category?: string;
          sort_order: number;
          is_active: boolean;
          created_at?: string;
          updated_at?: string;
          is_paid_add_on: boolean;
          default_add_on_price_cents?: number;
          catalog_kind: string;
          category_group?: string;
          capabilities: string[];
          suggested_add_on_price_cents?: number;
          supports_quantity: boolean;
        };
        Update: {
          id?: string | null;
          product_key?: string | null;
          name?: string | null;
          description?: string | null;
          category?: string | null;
          sort_order?: number | null;
          is_active?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
          is_paid_add_on?: boolean | null;
          default_add_on_price_cents?: number | null;
          catalog_kind?: string | null;
          category_group?: string | null;
          capabilities?: string[] | null;
          suggested_add_on_price_cents?: number | null;
          supports_quantity?: boolean | null;
        };
        Relationships: [];
      };
      "profiles": {
        Row: {
          id: string;
          email: string;
          full_name?: string;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          full_name?: string;
          active: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          email?: string | null;
          full_name?: string | null;
          active?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "purchase_items": {
        Row: {
          id: string;
          purchase_id: string;
          tenant_id: string;
          source_offer_item_id?: string;
          name: string;
          description?: string;
          quantity: number;
          unit_amount_cents: number;
          billing_type: string;
          billing_interval?: string;
          discount_summary?: string;
          stripe_product_id?: string;
          stripe_price_id?: string;
          service_status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          purchase_id: string;
          tenant_id: string;
          source_offer_item_id?: string;
          name: string;
          description?: string;
          quantity: number;
          unit_amount_cents: number;
          billing_type: string;
          billing_interval?: string;
          discount_summary?: string;
          stripe_product_id?: string;
          stripe_price_id?: string;
          service_status: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          purchase_id?: string | null;
          tenant_id?: string | null;
          source_offer_item_id?: string | null;
          name?: string | null;
          description?: string | null;
          quantity?: number | null;
          unit_amount_cents?: number | null;
          billing_type?: string | null;
          billing_interval?: string | null;
          discount_summary?: string | null;
          stripe_product_id?: string | null;
          stripe_price_id?: string | null;
          service_status?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "purchases": {
        Row: {
          id: string;
          tenant_id: string;
          offer_id?: string;
          status: string;
          currency: string;
          subtotal_cents: number;
          discount_total_cents: number;
          amount_due_today_cents: number;
          recurring_total_cents: number;
          stripe_customer_id?: string;
          stripe_checkout_session_id?: string;
          stripe_subscription_id?: string;
          stripe_payment_intent_id?: string;
          stripe_invoice_id?: string;
          purchased_by?: string;
          purchased_at?: string;
          purchase_snapshot: unknown;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          offer_id?: string;
          status: string;
          currency: string;
          subtotal_cents: number;
          discount_total_cents: number;
          amount_due_today_cents: number;
          recurring_total_cents: number;
          stripe_customer_id?: string;
          stripe_checkout_session_id?: string;
          stripe_subscription_id?: string;
          stripe_payment_intent_id?: string;
          stripe_invoice_id?: string;
          purchased_by?: string;
          purchased_at?: string;
          purchase_snapshot: unknown;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          offer_id?: string | null;
          status?: string | null;
          currency?: string | null;
          subtotal_cents?: number | null;
          discount_total_cents?: number | null;
          amount_due_today_cents?: number | null;
          recurring_total_cents?: number | null;
          stripe_customer_id?: string | null;
          stripe_checkout_session_id?: string | null;
          stripe_subscription_id?: string | null;
          stripe_payment_intent_id?: string | null;
          stripe_invoice_id?: string | null;
          purchased_by?: string | null;
          purchased_at?: string | null;
          purchase_snapshot?: unknown | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "role_permissions": {
        Row: {
          role_id: string;
          permission_id: string;
        };
        Insert: {
          role_id: string;
          permission_id: string;
        };
        Update: {
          role_id?: string | null;
          permission_id?: string | null;
        };
        Relationships: [];
      };
      "roles": {
        Row: {
          id: string;
          tenant_id?: string;
          slug: string;
          name: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id?: string;
          slug: string;
          name: string;
          created_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          slug?: string | null;
          name?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      "service_requests": {
        Row: {
          id: string;
          tenant_id: string;
          created_by?: string;
          request_type: string;
          title: string;
          description: string;
          status: string;
          admin_notes?: string;
          created_at: string;
          updated_at: string;
          completed_at?: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          created_by?: string;
          request_type: string;
          title: string;
          description: string;
          status: string;
          admin_notes?: string;
          created_at?: string;
          updated_at?: string;
          completed_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          created_by?: string | null;
          request_type?: string | null;
          title?: string | null;
          description?: string | null;
          status?: string | null;
          admin_notes?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      "stripe_webhook_events": {
        Row: {
          id: string;
          stripe_event_id: string;
          event_type: string;
          livemode: boolean;
          processed: boolean;
          processing_error?: string;
          payload?: unknown;
          received_at: string;
          processed_at?: string;
        };
        Insert: {
          id?: string;
          stripe_event_id: string;
          event_type: string;
          livemode: boolean;
          processed: boolean;
          processing_error?: string;
          payload?: unknown;
          received_at: string;
          processed_at?: string;
        };
        Update: {
          id?: string | null;
          stripe_event_id?: string | null;
          event_type?: string | null;
          livemode?: boolean | null;
          processed?: boolean | null;
          processing_error?: string | null;
          payload?: unknown | null;
          received_at?: string | null;
          processed_at?: string | null;
        };
        Relationships: [];
      };
      "tenant_activity_log": {
        Row: {
          id: string;
          tenant_id: string;
          actor_user_id?: string;
          actor_type: string;
          action: string;
          entity_type?: string;
          entity_id?: string;
          summary: string;
          metadata: unknown;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          actor_user_id?: string;
          actor_type: string;
          action: string;
          entity_type?: string;
          entity_id?: string;
          summary: string;
          metadata: unknown;
          created_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          actor_user_id?: string | null;
          actor_type?: string | null;
          action?: string | null;
          entity_type?: string | null;
          entity_id?: string | null;
          summary?: string | null;
          metadata?: unknown | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      "tenant_contacts": {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          email?: string;
          phone?: string;
          job_title?: string;
          contact_type: string;
          is_primary: boolean;
          is_billing_contact: boolean;
          is_technical_contact: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          name: string;
          email?: string;
          phone?: string;
          job_title?: string;
          contact_type: string;
          is_primary: boolean;
          is_billing_contact: boolean;
          is_technical_contact: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          name?: string | null;
          email?: string | null;
          phone?: string | null;
          job_title?: string | null;
          contact_type?: string | null;
          is_primary?: boolean | null;
          is_billing_contact?: boolean | null;
          is_technical_contact?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "tenant_internal_notes": {
        Row: {
          id: string;
          tenant_id: string;
          subject_type: string;
          subject_id?: string;
          body: string;
          created_by?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          subject_type: string;
          subject_id?: string;
          body: string;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          subject_type?: string | null;
          subject_id?: string | null;
          body?: string | null;
          created_by?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "tenant_memberships": {
        Row: {
          id: string;
          tenant_id: string;
          user_id: string;
          role_id: string;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          user_id: string;
          role_id: string;
          status: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          user_id?: string | null;
          role_id?: string | null;
          status?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "tenant_portal_settings": {
        Row: {
          tenant_id: string;
          website_status: string;
          website_url?: string;
          domain?: string;
          domain_owner?: string;
          registrar?: string;
          hosting_platform?: string;
          hosting_status: string;
          ssl_status: string;
          database_platform?: string;
          plan_name: string;
          monthly_price_cents: number;
          currency: string;
          intro_price_cents?: number;
          intro_expires_on?: string;
          contract_start_on?: string;
          updates_included_per_month: number;
          updates_used_this_month: number;
          last_deployment_at?: string;
          last_backup_at?: string;
          analytics_summary?: string;
          estimated_infra_cost_cents: number;
          support_email?: string;
          support_phone?: string;
          notes?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          tenant_id: string;
          website_status: string;
          website_url?: string;
          domain?: string;
          domain_owner?: string;
          registrar?: string;
          hosting_platform?: string;
          hosting_status: string;
          ssl_status: string;
          database_platform?: string;
          plan_name: string;
          monthly_price_cents: number;
          currency: string;
          intro_price_cents?: number;
          intro_expires_on?: string;
          contract_start_on?: string;
          updates_included_per_month: number;
          updates_used_this_month: number;
          last_deployment_at?: string;
          last_backup_at?: string;
          analytics_summary?: string;
          estimated_infra_cost_cents: number;
          support_email?: string;
          support_phone?: string;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          tenant_id?: string | null;
          website_status?: string | null;
          website_url?: string | null;
          domain?: string | null;
          domain_owner?: string | null;
          registrar?: string | null;
          hosting_platform?: string | null;
          hosting_status?: string | null;
          ssl_status?: string | null;
          database_platform?: string | null;
          plan_name?: string | null;
          monthly_price_cents?: number | null;
          currency?: string | null;
          intro_price_cents?: number | null;
          intro_expires_on?: string | null;
          contract_start_on?: string | null;
          updates_included_per_month?: number | null;
          updates_used_this_month?: number | null;
          last_deployment_at?: string | null;
          last_backup_at?: string | null;
          analytics_summary?: string | null;
          estimated_infra_cost_cents?: number | null;
          support_email?: string | null;
          support_phone?: string | null;
          notes?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "tenant_profiles": {
        Row: {
          tenant_id: string;
          legal_business_name?: string;
          display_name?: string;
          business_type?: string;
          primary_contact_name?: string;
          primary_contact_email?: string;
          primary_contact_phone?: string;
          billing_contact_name?: string;
          billing_contact_email?: string;
          website_url?: string;
          primary_domain?: string;
          support_email?: string;
          address_line_1?: string;
          address_line_2?: string;
          city?: string;
          state?: string;
          postal_code?: string;
          country: string;
          logo_url?: string;
          internal_status: string;
          onboarding_status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          tenant_id: string;
          legal_business_name?: string;
          display_name?: string;
          business_type?: string;
          primary_contact_name?: string;
          primary_contact_email?: string;
          primary_contact_phone?: string;
          billing_contact_name?: string;
          billing_contact_email?: string;
          website_url?: string;
          primary_domain?: string;
          support_email?: string;
          address_line_1?: string;
          address_line_2?: string;
          city?: string;
          state?: string;
          postal_code?: string;
          country: string;
          logo_url?: string;
          internal_status: string;
          onboarding_status: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          tenant_id?: string | null;
          legal_business_name?: string | null;
          display_name?: string | null;
          business_type?: string | null;
          primary_contact_name?: string | null;
          primary_contact_email?: string | null;
          primary_contact_phone?: string | null;
          billing_contact_name?: string | null;
          billing_contact_email?: string | null;
          website_url?: string | null;
          primary_domain?: string | null;
          support_email?: string | null;
          address_line_1?: string | null;
          address_line_2?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string | null;
          logo_url?: string | null;
          internal_status?: string | null;
          onboarding_status?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "tenant_subscriptions": {
        Row: {
          id: string;
          tenant_id: string;
          stripe_customer_id?: string;
          stripe_subscription_id?: string;
          stripe_price_id?: string;
          subscription_status: string;
          current_period_end?: string;
          created_at: string;
          updated_at: string;
          purchase_id?: string;
          current_period_start?: string;
          cancel_at_period_end: boolean;
          canceled_at?: string;
          standard_amount_cents?: number;
          current_discount_amount_cents?: number;
          current_effective_amount_cents?: number;
          discount_ends_at?: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          stripe_customer_id?: string;
          stripe_subscription_id?: string;
          stripe_price_id?: string;
          subscription_status: string;
          current_period_end?: string;
          created_at?: string;
          updated_at?: string;
          purchase_id?: string;
          current_period_start?: string;
          cancel_at_period_end: boolean;
          canceled_at?: string;
          standard_amount_cents?: number;
          current_discount_amount_cents?: number;
          current_effective_amount_cents?: number;
          discount_ends_at?: string;
        };
        Update: {
          id?: string | null;
          tenant_id?: string | null;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          stripe_price_id?: string | null;
          subscription_status?: string | null;
          current_period_end?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          purchase_id?: string | null;
          current_period_start?: string | null;
          cancel_at_period_end?: boolean | null;
          canceled_at?: string | null;
          standard_amount_cents?: number | null;
          current_discount_amount_cents?: number | null;
          current_effective_amount_cents?: number | null;
          discount_ends_at?: string | null;
        };
        Relationships: [];
      };
      "tenant_technical_profiles": {
        Row: {
          tenant_id: string;
          architecture_type?: string;
          repository_provider?: string;
          repository_owner?: string;
          repository_name?: string;
          repository_url?: string;
          default_branch?: string;
          hosting_provider?: string;
          hosting_project_name?: string;
          hosting_project_id?: string;
          production_url?: string;
          domain_registrar?: string;
          dns_provider?: string;
          primary_domain?: string;
          database_provider?: string;
          database_project_name?: string;
          database_project_reference?: string;
          database_region?: string;
          database_schema_name?: string;
          storage_provider?: string;
          storage_bucket_names?: string[];
          stripe_account_type?: string;
          stripe_connected_account_id?: string;
          email_provider?: string;
          email_sending_domain?: string;
          analytics_provider?: string;
          analytics_property_id?: string;
          source_code_ownership?: string;
          backup_policy?: string;
          last_backup_verified_at?: string;
          deployment_notes?: string;
          technical_notes?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          tenant_id: string;
          architecture_type?: string;
          repository_provider?: string;
          repository_owner?: string;
          repository_name?: string;
          repository_url?: string;
          default_branch?: string;
          hosting_provider?: string;
          hosting_project_name?: string;
          hosting_project_id?: string;
          production_url?: string;
          domain_registrar?: string;
          dns_provider?: string;
          primary_domain?: string;
          database_provider?: string;
          database_project_name?: string;
          database_project_reference?: string;
          database_region?: string;
          database_schema_name?: string;
          storage_provider?: string;
          storage_bucket_names?: string[];
          stripe_account_type?: string;
          stripe_connected_account_id?: string;
          email_provider?: string;
          email_sending_domain?: string;
          analytics_provider?: string;
          analytics_property_id?: string;
          source_code_ownership?: string;
          backup_policy?: string;
          last_backup_verified_at?: string;
          deployment_notes?: string;
          technical_notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          tenant_id?: string | null;
          architecture_type?: string | null;
          repository_provider?: string | null;
          repository_owner?: string | null;
          repository_name?: string | null;
          repository_url?: string | null;
          default_branch?: string | null;
          hosting_provider?: string | null;
          hosting_project_name?: string | null;
          hosting_project_id?: string | null;
          production_url?: string | null;
          domain_registrar?: string | null;
          dns_provider?: string | null;
          primary_domain?: string | null;
          database_provider?: string | null;
          database_project_name?: string | null;
          database_project_reference?: string | null;
          database_region?: string | null;
          database_schema_name?: string | null;
          storage_provider?: string | null;
          storage_bucket_names?: string[] | null;
          stripe_account_type?: string | null;
          stripe_connected_account_id?: string | null;
          email_provider?: string | null;
          email_sending_domain?: string | null;
          analytics_provider?: string | null;
          analytics_property_id?: string | null;
          source_code_ownership?: string | null;
          backup_policy?: string | null;
          last_backup_verified_at?: string | null;
          deployment_notes?: string | null;
          technical_notes?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      "tenants": {
        Row: {
          id: string;
          slug: string;
          display_name: string;
          status: string;
          platform_category: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          display_name: string;
          status: string;
          platform_category: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          slug?: string | null;
          display_name?: string | null;
          status?: string | null;
          platform_category?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      ma5_purge_expired_anonymous_visitors: {
        Args: { retention_days?: number };
        Returns: number;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

export type Tables<
  T extends keyof Database["public"]["Tables"],
> = Database["public"]["Tables"][T]["Row"];

export type TablesInsert<
  T extends keyof Database["public"]["Tables"],
> = Database["public"]["Tables"][T]["Insert"];

export type TablesUpdate<
  T extends keyof Database["public"]["Tables"],
> = Database["public"]["Tables"][T]["Update"];
