import type {
  BusinessReports,
  DailyOpsDashboard,
} from "@/features/analytics/types";

/** Demo Daily Ops — what Mike opens every morning. */
export const DEMO_DAILY_OPS: DailyOpsDashboard = {
  health: [
    {
      id: "revenue",
      label: "Revenue",
      value: "↑ 8%",
      detail: "vs last week",
      status: "good",
    },
    {
      id: "memberships",
      label: "Memberships",
      value: "+4",
      detail: "net this month",
      status: "good",
    },
    {
      id: "attendance",
      label: "Attendance",
      value: "91%",
      detail: "last 7 days",
      status: "watch",
    },
    {
      id: "failed-payments",
      label: "Failed payments",
      value: "2",
      detail: "need follow-up",
      status: "alert",
    },
  ],
  overview: [
    {
      id: "sessions",
      label: "Today's sessions",
      value: "18",
      href: "/admin/schedule",
    },
    {
      id: "revenue",
      label: "Today's revenue",
      value: "$1,140",
      href: "/admin/reports",
    },
    {
      id: "attendance",
      label: "Attendance rate",
      value: "94%",
      href: "/admin/bookings",
    },
    {
      id: "members",
      label: "Active members",
      value: "71",
      href: "/admin/clients",
    },
    {
      id: "messages",
      label: "Unread messages",
      value: "3",
      href: "/admin/messages",
    },
    {
      id: "failed",
      label: "Failed payments",
      value: "1",
      href: "/admin/clients",
    },
  ],
  schedule: [
    {
      id: "s1",
      time: "6:00 AM",
      title: "Small Group Training",
      coach: "Robert",
      booked: 9,
      capacity: 10,
      href: "/admin/bookings",
    },
    {
      id: "s2",
      time: "9:00 AM",
      title: "Sports Performance",
      coach: "Mike",
      booked: 7,
      capacity: 8,
      href: "/admin/bookings",
    },
    {
      id: "s3",
      time: "12:00 PM",
      title: "Fitness Assessment",
      coach: "Robert",
      booked: 1,
      capacity: 1,
      href: "/admin/bookings",
    },
    {
      id: "s4",
      time: "4:00 PM",
      title: "Small Group Training",
      coach: "Robert",
      booked: 10,
      capacity: 10,
      href: "/admin/bookings",
    },
    {
      id: "s5",
      time: "6:00 PM",
      title: "Small Group Training",
      coach: "Mike",
      booked: 18,
      capacity: 20,
      href: "/admin/bookings",
    },
    {
      id: "s6",
      time: "7:30 PM",
      title: "Infrared Sauna",
      coach: "—",
      booked: 1,
      capacity: 1,
      href: "/admin/bookings",
    },
  ],
  payments: [
    {
      id: "p1",
      clientName: "Jordan Lee",
      amountCents: 19900,
      status: "paid",
      when: "8:14 AM",
      product: "Unlimited Membership",
    },
    {
      id: "p2",
      clientName: "Emily Chen",
      amountCents: 3000,
      status: "paid",
      when: "7:52 AM",
      product: "Drop-in session",
    },
    {
      id: "p3",
      clientName: "Chris Rivera",
      amountCents: 14900,
      status: "failed",
      when: "6:01 AM",
      product: "8-Pack Training",
    },
    {
      id: "p4",
      clientName: "Sam Patel",
      amountCents: 19900,
      status: "pending",
      when: "Yesterday",
      product: "Unlimited Membership",
    },
  ],
  signups: [
    {
      id: "n1",
      clientName: "Emily Chen",
      plan: "Unlimited Membership",
      when: "Today",
    },
    {
      id: "n2",
      clientName: "Marcus Webb",
      plan: "8-Pack Training",
      when: "Yesterday",
    },
    {
      id: "n3",
      clientName: "Taylor Brooks",
      plan: "Sports Performance",
      when: "Mon",
    },
  ],
  messages: [
    {
      id: "m1",
      from: "Alex",
      preview: "Can I switch Thursday to Friday?",
      when: "12 min ago",
      unread: true,
    },
    {
      id: "m2",
      from: "Jordan Lee",
      preview: "Thanks for the form check yesterday.",
      when: "Yesterday",
      unread: true,
    },
    {
      id: "m3",
      from: "Sam Patel",
      preview: "When does my pause end?",
      when: "Mon",
      unread: true,
    },
  ],
};

/** Demo Reports — business trends Mike checks for health at a glance. */
export const DEMO_BUSINESS_REPORTS: BusinessReports = {
  revenuePeriods: [
    { id: "today", label: "Today", value: "$1,140" },
    { id: "week", label: "This week", value: "$6,820" },
    { id: "month", label: "This month", value: "$28,450" },
    { id: "ytd", label: "YTD", value: "$186,200", note: "Jan–Jul" },
    { id: "last-year", label: "Last year", value: "$312,400" },
  ],
  revenueChart: [
    { label: "Jan", value: 22400 },
    { label: "Feb", value: 24100 },
    { label: "Mar", value: 26800 },
    { label: "Apr", value: 25900 },
    { label: "May", value: 28100 },
    { label: "Jun", value: 27450 },
    { label: "Jul", value: 28450 },
  ],
  bookingPeriods: [
    { id: "today", label: "Today", value: "42" },
    { id: "week", label: "This week", value: "186" },
    { id: "month", label: "This month", value: "712" },
    { id: "year", label: "This year", value: "4,180" },
  ],
  bookingsChart: [
    { label: "Mon", value: 38 },
    { label: "Tue", value: 42 },
    { label: "Wed", value: 35 },
    { label: "Thu", value: 44 },
    { label: "Fri", value: 41 },
    { label: "Sat", value: 28 },
    { label: "Sun", value: 18 },
  ],
  memberships: {
    active: 71,
    newThisMonth: 6,
    cancelled: 2,
    netGrowth: 4,
    atRisk: 5,
    expired: 3,
  },
  attendance: {
    ratePercent: 91,
    missedSessions: 14,
    averageAttendance: 8.4,
  },
  capacity: [
    { id: "c1", label: "Mon 6:00 PM · Small Group", booked: 18, capacity: 20 },
    { id: "c2", label: "Tue 6:00 AM · Small Group", booked: 9, capacity: 10 },
    { id: "c3", label: "Wed 4:00 PM · Sports Perf.", booked: 7, capacity: 8 },
    { id: "c4", label: "Thu 6:00 PM · Small Group", booked: 20, capacity: 20 },
    { id: "c5", label: "Fri 9:00 AM · Small Group", booked: 8, capacity: 10 },
  ],
  averageCapacityPercent: 87,
  topPrograms: [
    {
      id: "prog1",
      name: "Strength Foundations",
      members: 32,
      changePercent: 12,
    },
    {
      id: "prog2",
      name: "Athlete Performance",
      members: 21,
      changePercent: 6,
    },
    {
      id: "prog3",
      name: "MA5 Recovery",
      members: 14,
      changePercent: -3,
    },
  ],
  payments: {
    successful: 64,
    failed: 2,
    outstandingCents: 44700,
    refunds: 1,
  },
  activity: [
    { id: "a1", text: "John booked a session", when: "14 min ago" },
    { id: "a2", text: "Sarah renewed membership", when: "42 min ago" },
    { id: "a3", text: "Mike completed payment", when: "1 hr ago" },
    { id: "a4", text: "Coach added program block", when: "2 hr ago" },
    { id: "a5", text: "Emily joined MA5", when: "3 hr ago" },
  ],
  kpis: [
    { id: "k1", label: "Revenue today", value: "$1,140" },
    { id: "k2", label: "Revenue this week", value: "$6,820" },
    { id: "k3", label: "Revenue this month", value: "$28,450" },
    { id: "k4", label: "Revenue YTD", value: "$186,200" },
    { id: "k5", label: "Active members", value: "71" },
    { id: "k6", label: "New members this month", value: "6" },
    { id: "k7", label: "Expired memberships", value: "3" },
    { id: "k8", label: "Members at risk", value: "5" },
    { id: "k9", label: "Today's sessions", value: "18" },
    { id: "k10", label: "This week's sessions", value: "64" },
    { id: "k11", label: "Bookings this month", value: "712" },
    { id: "k12", label: "Average attendance", value: "8.4" },
    { id: "k13", label: "Successful payments", value: "64" },
    { id: "k14", label: "Failed payments", value: "2" },
    { id: "k15", label: "Outstanding balances", value: "$447" },
    { id: "k16", label: "Refunds", value: "1" },
  ],
};
